branches:
  only:
    - master

version: 0.3.2.{build}

build_script:
  - cd build
  - Package.build.cmd

artifacts:
  - path: releases\*.nupkg

cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified 
  
deploy:
  provider: NuGet
  api_key:
    secure: cOErtJQNPk64rHATxlhnmKgYsqvnGwHPo30EtqoAg7e2VES5rmBLfHVoNx4+qoac
  skip_symbols: false
  artifact: /.*\.nupkg/
  symbol_server: http://nuget.smbsrc.net